import { readFileSync } from 'node:fs';
import path from 'node:path';
import { defineConfig, devices } from '@playwright/test';

// E2E (F0-08) runs against the Supabase stack started with `supabase start` (docs/ops/SUPABASE.md),
// locally and in the `e2e` job of CI (F0-02d). Locally the web server is `astro dev`; with `CI` set
// it builds once and serves the static output with `astro preview`, so no test pays for the cold
// reload of the dev server (#219). The public Supabase variables default to the local values of
// .env.example when the shell does not set them.
const IS_CI = Boolean(process.env.CI);
const PORT = 4321;
// astro is called directly (no pnpm in between) so Playwright owns the process.
const ASTRO = 'node node_modules/astro/bin/astro.mjs';
const SERVER_ARGS = `--host 127.0.0.1 --port ${PORT}`;
const BASE_URL = `http://127.0.0.1:${PORT}`;
const PUBLIC_ENV_NAMES = ['PUBLIC_SUPABASE_URL', 'PUBLIC_SUPABASE_ANON_KEY'] as const;

function readEnvExample(): Record<string, string> {
  const file = readFileSync(path.resolve(import.meta.dirname, '../../.env.example'), 'utf8');
  return Object.fromEntries(
    file
      .split('\n')
      .map((line) => line.trim())
      .filter((line) => line !== '' && !line.startsWith('#'))
      .map((line) => {
        const separator = line.indexOf('=');
        return [line.slice(0, separator), line.slice(separator + 1)];
      }),
  );
}

function webServerEnv(): Record<string, string> {
  const defaults = readEnvExample();
  return {
    ...Object.fromEntries(
      PUBLIC_ENV_NAMES.map((name) => [name, process.env[name] ?? defaults[name] ?? '']),
    ),
    // Astro 7 detaches `astro dev` into a background daemon when it detects an AI agent shell
    // (am-i-vibing reads this variable). Playwright needs the server in the foreground to own it.
    CLAUDECODE: '',
  };
}

export default defineConfig({
  testDir: 'e2e',
  // Visual snapshots of /dev/widgets are committed as e2e/visual/<name>-<platform>.png (F2-01a):
  // -win32 for local runs, -linux for CI. The -linux ones are generated by CI, never by hand:
  //   1. Push the branch; the `e2e` job fails on each new or changed capture and uploads the
  //      `e2e-report` artifact, whose test-results/ holds <name>-actual.png per capture.
  //   2. `gh run download <run-id> -n e2e-report -D <tmp>`.
  //   3. Copy each <name>-actual.png to e2e/visual/<name>-linux.png, review and commit it.
  snapshotPathTemplate: '{testDir}/visual/{arg}-{platform}{ext}',
  fullyParallel: true,
  forbidOnly: true,
  retries: 0,
  // In CI the HTML report is uploaded with test-results/ (traces) when the job fails.
  reporter: IS_CI ? [['list'], ['html', { open: 'never' }]] : 'list',
  use: {
    baseURL: BASE_URL,
    trace: 'retain-on-failure',
  },
  projects: [{ name: 'chromium', use: { ...devices['Desktop Chrome'] } }],
  webServer: {
    // --ignore-lock skips the lock file of Astro 7, which a previous aborted dev run may have left.
    command: IS_CI
      ? `${ASTRO} build && ${ASTRO} preview ${SERVER_ARGS}`
      : `${ASTRO} dev --ignore-lock ${SERVER_ARGS}`,
    url: BASE_URL,
    reuseExistingServer: !IS_CI,
    // The CI command includes the production build.
    timeout: IS_CI ? 300_000 : 120_000,
    env: webServerEnv(),
  },
});
