export {
  DEFAULT_CONTINUITY_TOLERANCE_M,
  DEFAULT_SNAP_TOLERANCE_M,
  HISTORY_LIMIT,
  addArc,
  addLine,
  canRedo,
  canUndo,
  continuity,
  createHistory,
  emptyEditor,
  fromJson,
  fromPreset,
  moveEndpoint,
  push,
  redo,
  removeSegment,
  segmentEndpoints,
  select,
  setLineWidth,
  setRadius,
  snap,
  toJson,
  undo,
} from './mobile/trackEditor';
export type {
  ContinuityReport,
  EditorState,
  Endpoint,
  History,
  TrackGap,
} from './mobile/trackEditor';
export {
  ARC_RADIUS_FACTOR,
  PICK_TOLERANCE_M,
  TRACK_FILE_NAME,
  TrackEditor,
  arcFromDrag,
  downloadJson,
  readFileText,
  useTrackEditor,
} from './mobile/trackEditor';
export type {
  DownloadTrigger,
  DragArc,
  TrackDraft,
  TrackEditorApi,
  TrackEditorProps,
  TrackTool,
  UseTrackEditorOptions,
} from './mobile/trackEditor';

export {
  CATALOG_MOBILE_IDS,
  catalogMobileUrl,
  isCatalogMobileId,
  loadCatalogMobile,
  loadCatalogMobileAll,
  summaryOf,
} from './mobile/catalog';
export type {
  CatalogMobileEntry,
  CatalogMobileId,
  LoadCatalogMobileOptions,
} from './mobile/catalog';

export {
  CONTROLLERS,
  CONTROLLER_IDS,
  ControllerPanel,
  MANUAL_DIFF_RADPS,
  MANUAL_KEYSHORTCUTS,
  MANUAL_STEP_RADPS,
  ManualControls,
  ManualHelp,
  ManualViewer,
  commandOf,
  useManualKeyboard,
  useManualMode,
  HANDLE_RADIUS_M,
  LineFollowerView,
  LineFollowerWidget,
  START_BAND_M,
  S_STEP_M,
  StartPoseHandle,
  StartPoseMarker,
  TANGENT_STEP_M,
  TRACK_INDEX_STEP_M,
  buildTrackIndex,
  controllerParams,
  createLineFollowerModel,
  crossedStart,
  isControllerId,
  poseOnTrack,
  projectOnTrack,
  resolveTrack,
  startPoseOf,
  useLineFollower,
  viewOf,
} from './mobile/lineFollower';
export type {
  ControllerDef,
  ControllerId,
  ControllerPanelProps,
  ControllerParams,
  ManualControlsProps,
  ManualDrive,
  ManualKey,
  UseManualKeyboardOptions,
  LineFollowerApi,
  LineFollowerInput,
  LineFollowerOptions,
  LineFollowerPlot,
  LineFollowerState,
  LineFollowerViewProps,
  LineFollowerWidgetProps,
  Pose,
  StartPose,
  StartPoseControl,
  StartPoseHandleProps,
  TrackIndex,
  TrackJson,
  TrackPreset,
  TrackSample,
  UseLineFollowerOptions,
} from './mobile/lineFollower';

// Playground-only discovery/rendering (docs/STANDARDS.md §4: index.ts reexports the public
// API only); the implementation lives in ./dev/SimGallery.
export { SimGallery, stories } from './dev/SimGallery';
export type { SimGalleryProps, SimStories, SimStory } from './dev/SimGallery';
