import { readFileSync, readdirSync } from 'node:fs';
import { basename, join, relative, sep } from 'node:path';
import { gzipSync } from 'node:zlib';
import { beforeAll, describe, expect, test } from 'vitest';

/**
 * Regression guard of the budget of `docs/ARCHITECTURE.md` §8 (#154): `three` only on
 * 3D pages and ≤ 250 kB of compressed JS on the topic page.
 *
 * The test reads `apps/web/dist`, which only exists after `pnpm build`, so without that directory
 * it fails instead of being skipped (#208): a budget that is silently skipped is not a guard.
 * That is why `vitest.config.ts` excludes this file from the normal `pnpm test` and CI runs it with
 * `BUNDLE_BUDGET=1` in its own step of the `build` job, after `pnpm build`.
 */

const DIST_DIR = join(import.meta.dirname, '..', '..', '..', 'dist');
const ASSETS_DIR = join(DIST_DIR, '_astro');

/** 3D pages: the only ones that may download the `three` chunk (ARCHITECTURE §8). */
const PAGES_3D = ['simuladores/brazo/index.html', 'dev/widgets/index.html', 'dev/sims/index.html'];

/** Topic page generated by the content route; its budget is 250 kB gzip. */
const TEMA_PAGE = 'ruta/ruta-1/m00/t01/index.html';

const THEME_BUDGET_GZIP_BYTES = 250 * 1024;

/** Fails early and with instructions if the build has not been run (#208). */
function requireDist(): void {
  try {
    readdirSync(ASSETS_DIR);
  } catch {
    throw new Error(
      `No existe ${ASSETS_DIR}: el presupuesto de bundle necesita un build. ` +
        'Ejecuta `pnpm build` y vuelve a lanzar ' +
        '`BUNDLE_BUDGET=1 pnpm --filter @trayectoria/web exec vitest run`.',
    );
  }
}

function assetNames(): string[] {
  return readdirSync(ASSETS_DIR).filter((name) => name.endsWith('.js'));
}

/**
 * Graph of **static** imports between chunks: only the edges the browser downloads when
 * loading the page. A dynamic `import()` appears in the chunk's `__vite__mapDeps` table and is not
 * downloaded until it runs, so it does not count towards the budget.
 */
function staticImportGraph(assets: readonly string[]): Map<string, string[]> {
  const graph = new Map<string, string[]>();
  for (const asset of assets) {
    const source = readFileSync(join(ASSETS_DIR, asset), 'utf8');
    const edges = new Set<string>();
    const pattern = /(?:from|import)\s*["']\.\/([\w.-]+\.js)["']/g;
    let match: RegExpExecArray | null;
    while ((match = pattern.exec(source)) !== null) {
      const target = match[1];
      if (target !== undefined && target !== asset && assets.includes(target)) edges.add(target);
    }
    graph.set(asset, [...edges]);
  }
  return graph;
}

/** Chunks the page downloads: its entries plus the transitive closure of static imports. */
function downloadedChunks(page: string, graph: Map<string, string[]>): Set<string> {
  const html = readFileSync(join(DIST_DIR, ...page.split('/')), 'utf8');
  const entries = new Set<string>();
  const pattern = /_astro\/([\w.-]+\.js)/g;
  let match: RegExpExecArray | null;
  while ((match = pattern.exec(html)) !== null) {
    const entry = match[1];
    if (entry !== undefined) entries.add(entry);
  }

  const reached = new Set(entries);
  const pending = [...entries];
  while (pending.length > 0) {
    const current = pending.pop() as string;
    for (const next of graph.get(current) ?? []) {
      if (!reached.has(next)) {
        reached.add(next);
        pending.push(next);
      }
    }
  }
  return reached;
}

/**
 * Closure of a chunk including **dynamic** imports (any chunk name that appears in
 * its code, also in `__vite__mapDeps`): everything the page may end up downloading.
 */
function reachableChunks(page: string, assets: readonly string[]): Set<string> {
  const html = readFileSync(join(DIST_DIR, ...page.split('/')), 'utf8');
  const reached = new Set([...html.matchAll(/_astro\/([\w.-]+\.js)/g)].map((m) => m[1] as string));
  const pending = [...reached];
  while (pending.length > 0) {
    const source = readFileSync(join(ASSETS_DIR, pending.pop() as string), 'utf8');
    for (const match of source.matchAll(/["'](?:\.\/|\/?_astro\/)?([\w.-]+\.js)["']/g)) {
      const next = match[1] as string;
      if (assets.includes(next) && !reached.has(next)) {
        reached.add(next);
        pending.push(next);
      }
    }
  }
  return reached;
}

function gzipBytes(chunks: Iterable<string>): number {
  let total = 0;
  for (const chunk of chunks) total += gzipSync(readFileSync(join(ASSETS_DIR, chunk))).length;
  return total;
}

function htmlPages(): string[] {
  const pages: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) {
        if (entry.name !== '_astro') walk(full);
      } else if (entry.name.endsWith('.html')) {
        pages.push(relative(DIST_DIR, full).split(sep).join('/'));
      }
    }
  };
  walk(DIST_DIR);
  return pages;
}

/** The `three` chunk is the one containing `Frame`, the only module of `@trayectoria/widgets/scene3d`. */
function threeChunk(assets: readonly string[]): string | undefined {
  return assets.find((asset) => basename(asset).startsWith('Frame.'));
}

describe('presupuesto de bundle (ARCHITECTURE §8)', () => {
  beforeAll(requireDist);

  test('ninguna página fuera de las 3D referencia el chunk de three', () => {
    const assets = assetNames();
    const three = threeChunk(assets);
    expect(three, 'no se encontró el chunk de three en dist/_astro').toBeDefined();

    const graph = staticImportGraph(assets);
    const offenders = htmlPages()
      .filter((page) => !PAGES_3D.includes(page))
      .filter((page) => {
        // The HTML must not name it (`<script>`, `modulepreload`) nor reach it through static
        // imports, nor leave it in the `__vite__mapDeps` table of a chunk it does download: that
        // edge is the one that put `three` in the graph of the non-3D pages (#154).
        const reached = downloadedChunks(page, graph);
        if (reached.has(three as string)) return true;
        return [...reached].some((chunk) =>
          readFileSync(join(ASSETS_DIR, chunk), 'utf8').includes(three as string),
        );
      });
    expect(offenders).toEqual([]);
  });

  // Active since #188: `@trayectoria/widgets` exposes one entry per widget (ADR-0009) and the
  // topic page resolves each one with a dynamic `import()` from its entry, so it no longer
  // downloads the whole catalogue through the barrel.
  test('la página de tema carga como mucho 250 kB gzip de JS (#188)', () => {
    const graph = staticImportGraph(assetNames());
    const bytes = gzipBytes(downloadedChunks(TEMA_PAGE, graph));
    expect(bytes).toBeLessThanOrEqual(THEME_BUDGET_GZIP_BYTES);
  });

  // F7-02: `RobotSession` (in the base layout, every page) loads `robotPersistence` with
  // `import()`; if that module imports the `@trayectoria/widgets` barrel, any page
  // downloads the whole catalogue (KaTeX included) after hydrating. The 404 page only has the layout.
  test('el layout base no descarga el catálogo de widgets ni por import dinámico (F7-02)', () => {
    const assets = assetNames();
    const catalog = [...reachableChunks('404.html', assets)].filter((chunk) =>
      /^(Formula|DiffDriveWidget|Plot)\./.test(chunk),
    );
    expect(catalog).toEqual([]);
  });

  // F7-02b (#444): the classroom and the account imported `Toast` from the barrel and downloaded the whole
  // catalogue on load; now they use the `@trayectoria/widgets/Toast` entry. Only the static graph
  // counts: the account can still reach it with the `import()` of `@trayectoria/sims` when saving
  // a robot (`lib/robots/storage.ts`), which is not downloaded when opening the page.
  test.each([
    'aula/index.html',
    'unirse/index.html',
    'cuenta/index.html',
    'cuenta/robots/index.html',
  ])('%s no descarga el catálogo de widgets al cargar (F7-02b)', (page) => {
    const graph = staticImportGraph(assetNames());
    const catalog = [...downloadedChunks(page, graph)].filter((chunk) =>
      /^(Formula|DiffDriveWidget|Plot)\./.test(chunk),
    );
    expect(catalog).toEqual([]);
  });
});
