-- Trayectoria · database and storage hardening (security audit 2026-09-26; lote SEC-DB).
-- #508 (invite codes and join_group), #509 (column and row bounds), #522 (storage `urdf`) and the
-- points of #527 that need a migration (listed in PR #632). No earlier migration is edited: every
-- change is an `alter`, a `create or replace` or a drop and re-create here.
--
-- Every new bound follows the pattern of 0007/0008: a check constraint, or a `before insert`
-- trigger that raises `23514` with the name of the limit as the constraint, so the client tells
-- them apart by that name. Check constraints are validated against the existing rows: if one were
-- already out of bounds, the migration would fail here instead of leaving a table that breaks its
-- own constraint.

-- #527.1 · New relations and functions in `public` are closed to `anon` by default -------------
-- `revoke all on all tables ... from anon` (0002) only covered the tables that existed then; each
-- later migration revoked by hand. The default privileges of the migration role still granted
-- `anon` everything on new tables, sequences and functions.

alter default privileges for role postgres in schema public revoke all on tables from anon;
alter default privileges for role postgres in schema public revoke all on sequences from anon;
alter default privileges for role postgres in schema public revoke all on functions from anon;

-- #527.2 · `set_updated_at` is a trigger function; PostgREST would list it as RPC (as in 0008).
revoke all on function public.set_updated_at() from public, anon, authenticated;

-- #508 · Invite codes are generated by the database ----------------------------------------------
-- The client generated the code and wrote it, so any teacher could set `invite_code = 'A'`, and
-- the unique index answered `23505` for an existing code (an oracle without joining). Now the code
-- comes only from `generate_invite_code()`: 8 characters of the dictation-friendly alphabet the
-- classroom already uses (no I, O, 0 or 1), from `gen_random_bytes`. 256 is a multiple of 32, so
-- `byte % 32` is uniform. `authenticated` keeps insert on `id`, `owner_id`, `name` and update on
-- `name` only; the code is set by the column default on insert and by `regenerate_invite_code()`.

create function public.generate_invite_code() returns text
language sql volatile set search_path = '' as $$
  select string_agg(
    substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', get_byte(r.bytes, i.position) % 32 + 1, 1),
    '' order by i.position
  )
  from (select extensions.gen_random_bytes(8) as bytes) as r,
       generate_series(0, 7) as i (position);
$$;

-- The column default calls it with the privileges of the inserting user, so `authenticated` keeps
-- `execute`: as an RPC it only returns a random string, never an existing code.
revoke all on function public.generate_invite_code() from public, anon;
grant execute on function public.generate_invite_code() to authenticated;

alter table public.groups alter column invite_code set default public.generate_invite_code();
alter table public.groups
  add constraint groups_invite_code_format check (invite_code ~ '^[A-Z0-9]{8,}$');

revoke insert, update on public.groups from authenticated;
grant insert (id, owner_id, name) on public.groups to authenticated;
grant update (name) on public.groups to authenticated;

-- The owner replaces the code of their group. A collision with another group's code (1 in 2^40
-- per existing group) draws again, at most five times.
create function public.regenerate_invite_code(target_group_id uuid) returns text
language plpgsql security definer set search_path = '' as $$
declare
  new_code text;
begin
  if not public.owns_group(target_group_id) then
    raise exception 'group not found' using errcode = 'P0001';
  end if;
  for draw in 1..5 loop
    new_code := public.generate_invite_code();
    begin
      update public.groups set invite_code = new_code where id = target_group_id;
      return new_code;
    exception when unique_violation then
      null;
    end;
  end loop;
  raise exception 'invite code collision' using errcode = 'P0001';
end;
$$;

revoke all on function public.regenerate_invite_code(uuid) from public, anon;
grant execute on function public.regenerate_invite_code(uuid) to authenticated;

-- #508 · Failed attempts of join_group ------------------------------------------------------------
-- At most 10 failed joins per user in 10 minutes. The failures are rows of `join_attempts`, which
-- no API role can read or write. A failed join now returns `null` instead of raising: a raise
-- would roll back the row that counts the failure, so the limit would never be reached. Unknown
-- code, own group and existing membership still give the same answer. Past the limit the function
-- raises `too many join attempts` before looking at the code. The rows older than the window are
-- deleted on every call of the same user, so there is no periodic clean-up.

create table public.join_attempts (
  user_id uuid not null references public.profiles (id) on delete cascade,
  attempted_at timestamptz not null default now()
);

create index join_attempts_user_id_attempted_at_idx
  on public.join_attempts (user_id, attempted_at);

alter table public.join_attempts enable row level security;
revoke all on public.join_attempts from anon, authenticated;

create or replace function public.join_group(invite_code text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  caller_id uuid := auth.uid();
  found_group_id uuid;
  found_owner_id uuid;
begin
  if caller_id is null then
    raise exception 'invalid invite code' using errcode = 'P0001';
  end if;

  -- Concurrent calls of the same user count one after the other.
  perform pg_advisory_xact_lock(hashtextextended('join_group:' || caller_id::text, 0));
  delete from public.join_attempts
   where user_id = caller_id and attempted_at < now() - interval '10 minutes';
  if (select count(*) from public.join_attempts where user_id = caller_id) >= 10 then
    raise exception 'too many join attempts' using errcode = 'P0001';
  end if;

  select g.id, g.owner_id
    into found_group_id, found_owner_id
    from public.groups g
   where g.invite_code = join_group.invite_code;

  if found_group_id is null
     or found_owner_id = caller_id
     or exists (
       select 1 from public.group_members m
        where m.group_id = found_group_id and m.user_id = caller_id
     )
  then
    insert into public.join_attempts (user_id) values (caller_id);
    return null;
  end if;

  insert into public.group_members (group_id, user_id) values (found_group_id, caller_id);
  return found_group_id;
end;
$$;

-- #527.3 · `groups_visible` without `owner_id`: members only need the name --------------------
drop view public.groups_visible;

create view public.groups_visible
  with (security_invoker = false, security_barrier = true)
as
  select g.id, g.name, g.created_at
  from public.groups g
  where g.owner_id = auth.uid() or public.is_group_member(g.id);

revoke all on public.groups_visible from public, anon;
grant select on public.groups_visible to authenticated;

-- #509 · Bounds of the text columns ----------------------------------------------------------------
-- `tracks.name` already had one (0006). Topic ids are those of docs/ARCHITECTURE.md §5.1 plus the
-- reserve rows of 0012 (`reserva/caida-libre`, `reserva/tiro-parabolico`); exercise ids are `eN`,
-- or `mMM-tTT/eN` for the exercises that 0012 kept from the removed ones.

alter table public.profiles
  add constraint profiles_display_name_length check (char_length(display_name) between 1 and 80);
alter table public.groups
  add constraint groups_name_length check (char_length(name) between 1 and 80);
alter table public.robots
  add constraint robots_name_length check (char_length(name) between 1 and 80);

alter table public.progress
  add constraint progress_topic_id_format
    check (topic_id ~ '^(ruta-[0-9]+/m[0-9]{2}-t[0-9]{2}|reserva/[a-z0-9-]+)$');
alter table public.attempts
  add constraint attempts_topic_id_format
    check (topic_id ~ '^(ruta-[0-9]+/m[0-9]{2}-t[0-9]{2}|reserva/[a-z0-9-]+)$');
alter table public.attempts
  add constraint attempts_exercise_id_format
    check (exercise_id ~ '^(m[0-9]{2}-t[0-9]{2}/)?e[0-9]{1,3}$');

alter table public.progress
  add constraint progress_best_score_range check (best_score is null or best_score between 0 and 1);

-- #509.4, #522.4 · The only value the client writes: `urdf/{owner}/{robot}.zip`.
alter table public.robots
  add constraint robots_urdf_path_format
    check (urdf_path is null or urdf_path = 'urdf/' || owner_id::text || '/' || id::text || '.zip');

-- #509.6 · A huge name in the sign-up metadata is cut, not a failed sign-up. Same body as 0010.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, role)
  values (
    new.id,
    coalesce(
      nullif(trim(left(trim(new.raw_user_meta_data ->> 'display_name'), 80)), ''),
      'Estudiante'
    ),
    case when new.raw_user_meta_data ->> 'role' = 'teacher' then 'teacher' else 'student' end
  );
  return new;
end;
$$;

-- #509.5 · Rows per owner: 500 progress rows per learner, 50 groups per teacher, 50 memberships
-- per user. Same shape as 0008. `progress` is written with an upsert on `(user_id, topic_id)`, so
-- writing an existing topic again adds no row and is let through, like `tracks` in 0008.
-- Memberships are inserted by `join_group` as the function owner, so that count is not under RLS.

create function public.enforce_progress_owner_limit() returns trigger
language plpgsql set search_path = '' as $$
begin
  perform pg_advisory_xact_lock(hashtextextended('progress:' || new.user_id::text, 0));
  if exists (
    select 1 from public.progress where user_id = new.user_id and topic_id = new.topic_id
  ) then
    return new;
  end if;
  if (select count(*) from public.progress where user_id = new.user_id) >= 500 then
    raise exception using
      errcode = 'check_violation',
      constraint = 'progress_owner_row_limit',
      message = 'new row for relation "progress" violates check constraint "progress_owner_row_limit"';
  end if;
  return new;
end;
$$;

create function public.enforce_groups_owner_limit() returns trigger
language plpgsql set search_path = '' as $$
begin
  perform pg_advisory_xact_lock(hashtextextended('groups:' || new.owner_id::text, 0));
  if (select count(*) from public.groups where owner_id = new.owner_id) >= 50 then
    raise exception using
      errcode = 'check_violation',
      constraint = 'groups_owner_row_limit',
      message = 'new row for relation "groups" violates check constraint "groups_owner_row_limit"';
  end if;
  return new;
end;
$$;

create function public.enforce_group_members_owner_limit() returns trigger
language plpgsql set search_path = '' as $$
begin
  perform pg_advisory_xact_lock(hashtextextended('group_members:' || new.user_id::text, 0));
  if (select count(*) from public.group_members where user_id = new.user_id) >= 50 then
    raise exception using
      errcode = 'check_violation',
      constraint = 'group_members_owner_row_limit',
      message = 'new row for relation "group_members" violates check constraint "group_members_owner_row_limit"';
  end if;
  return new;
end;
$$;

revoke all on function public.enforce_progress_owner_limit() from public, anon, authenticated;
revoke all on function public.enforce_groups_owner_limit() from public, anon, authenticated;
revoke all on function public.enforce_group_members_owner_limit() from public, anon, authenticated;

create trigger progress_owner_row_limit
  before insert on public.progress
  for each row execute function public.enforce_progress_owner_limit();

create trigger groups_owner_row_limit
  before insert on public.groups
  for each row execute function public.enforce_groups_owner_limit();

create trigger group_members_owner_row_limit
  before insert on public.group_members
  for each row execute function public.enforce_group_members_owner_limit();

-- #527.4 · Policies call `(select auth.uid())`: evaluated once per statement, not once per row ---
-- Same rules as 0002, 0005 and 0006; only the call changes.

alter policy "profiles: read own or taught" on public.profiles
  using (id = (select auth.uid()) or public.teaches_user(id));
alter policy "profiles: update own" on public.profiles
  using (id = (select auth.uid()))
  with check (id = (select auth.uid()));

alter policy "groups: owner reads" on public.groups
  using (owner_id = (select auth.uid()));
alter policy "groups: teacher creates own" on public.groups
  with check (owner_id = (select auth.uid()) and public.is_teacher());
alter policy "groups: owner updates" on public.groups
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));
alter policy "groups: owner deletes" on public.groups
  using (owner_id = (select auth.uid()));

alter policy "group_members: member or owner reads" on public.group_members
  using (user_id = (select auth.uid()) or public.owns_group(group_id));
alter policy "group_members: member leaves" on public.group_members
  using (user_id = (select auth.uid()));

alter policy "robots: owner reads" on public.robots
  using (owner_id = (select auth.uid()));
alter policy "robots: owner inserts" on public.robots
  with check (owner_id = (select auth.uid()));
alter policy "robots: owner updates" on public.robots
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));
alter policy "robots: owner deletes" on public.robots
  using (owner_id = (select auth.uid()));

alter policy "progress: own or taught reads" on public.progress
  using (user_id = (select auth.uid()) or public.teaches_user(user_id));
alter policy "progress: owner inserts" on public.progress
  with check (user_id = (select auth.uid()));
alter policy "progress: owner updates" on public.progress
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));
alter policy "progress: owner deletes" on public.progress
  using (user_id = (select auth.uid()));

alter policy "attempts: own or taught reads" on public.attempts
  using (user_id = (select auth.uid()) or public.teaches_user(user_id));
alter policy "attempts: owner inserts" on public.attempts
  with check (user_id = (select auth.uid()));
alter policy "attempts: owner updates" on public.attempts
  using (user_id = (select auth.uid()))
  with check (user_id = (select auth.uid()));
alter policy "attempts: owner deletes" on public.attempts
  using (user_id = (select auth.uid()));

alter policy "tracks: owner reads" on public.tracks
  using (owner_id = (select auth.uid()));
alter policy "tracks: owner inserts" on public.tracks
  with check (owner_id = (select auth.uid()));
alter policy "tracks: owner updates" on public.tracks
  using (owner_id = (select auth.uid()))
  with check (owner_id = (select auth.uid()));
alter policy "tracks: owner deletes" on public.tracks
  using (owner_id = (select auth.uid()));

-- #522, #527.4, #527.5 · Storage `urdf` ------------------------------------------------------------
-- Uploads and moves must land on `{uid}/{robotId}.zip`, the only key the client writes
-- (`urdfObjectPath`), and need the caller's profile: a JWT still valid after `delete_account()`
-- has no profile, so it cannot leave orphan objects under a deleted uid. The bucket takes only
-- `application/zip`, the content type the client sends. Reads and deletes keep the folder rule.
-- Orphan prefixes are not swept by a periodic job in v1.

update storage.buckets set allowed_mime_types = array['application/zip'] where id = 'urdf';

alter policy "urdf: owner reads" on storage.objects
  using (bucket_id = 'urdf' and (storage.foldername(name))[1] = (select auth.uid())::text);

alter policy "urdf: owner uploads" on storage.objects
  with check (
    bucket_id = 'urdf'
    and name ~ ('^' || (select auth.uid())::text || '/[0-9a-f-]{36}\.zip$')
    and exists (select 1 from public.profiles p where p.id = (select auth.uid()))
  );

alter policy "urdf: owner updates" on storage.objects
  using (bucket_id = 'urdf' and (storage.foldername(name))[1] = (select auth.uid())::text)
  with check (
    bucket_id = 'urdf'
    and name ~ ('^' || (select auth.uid())::text || '/[0-9a-f-]{36}\.zip$')
    and exists (select 1 from public.profiles p where p.id = (select auth.uid()))
  );

alter policy "urdf: owner deletes" on storage.objects
  using (bucket_id = 'urdf' and (storage.foldername(name))[1] = (select auth.uid())::text);
